# Source: https://github.com/ozh/github-colors/blob/master/colors.json
import json
import re

from MDgen.util import rm

def run():
    with open("./git_colors.json", 'r') as f:
        st = f.read()
    
    dic = json.loads(st)
    
    colorinfos = ""
    
    for k, v in dic.items():
        nk = "_".join([st.lower() for st in re.sub('[^a-zA-Z]+', '_', k).split(" ")])
        colorinfos += f"\t{nk} = GitColorInfo(\"{v['color']}\", \"{v['url']}\", \"{k}\")\n"
    
    rm("../git_colors.py")
    
    with open("../git_colors.py", 'w') as f:
        f.write("## This file contains all the colors of github-supported languages\n")
        f.write("## Auto generated by ./make_colors.py ##\n")
        f.write("\n")
        f.write("from MDgen.chart.colorinfo import GitColorInfo\n")
        f.write("\n")
        f.write("class Colors:\n")
        f.write(colorinfos)

if __name__ == "__main__":
    run()