# Source: https://github.com/ozh/github-colors/blob/master/colors.json
import yaml
import re

from MDgen.util import rm

def run():
    with open("./../languages.yml", 'r') as f:
        dic: dict[str, dict] = yaml.safe_load(f)
    
    colorinfos = ""
    
    for k, v in dic.items():
        try:
            colorinfos += f"""\
    "{k}": GitLanguageInfo(
        color = "{v['color']}", 
        language_type = "{v['type']}", 
        language_id = {v['language_id']},
        name = "{k}",
        extension = {v['extensions']}
    ),
"""
        except KeyError:
            continue
    
    rm("../git_colors.py")
    
    with open("../git_colors.py", 'w') as f:
        f.write("## This file contains all the colors of github-supported languages\n")
        f.write("## Auto generated by ./make_colors.py ##\n")
        f.write("## YAML file obtained at https://github.com/github/linguist/blob/master/lib/linguist/languages.yml ##\n")
        f.write("\n")
        f.write("from MDgen.profile.git_language_info import GitLanguageInfo\n")
        f.write("\n")
        f.write("COLORS = {\n")
        f.write(colorinfos)
        f.write("}")

if __name__ == "__main__":
    run()